version: "3.7"

services:
  postgresql:
    image: postgres:17.0
    restart: always
    env_file:
      - postgresql.env
    ports:
      - 5432:5432
    volumes:
      - ./postgresql_data:/var/lib/postgresql/data
