version: '3.7'
services:
  rabbitmq:
    image: rabbitmq:4.0.3-management
    hostname: rabbitmq
    container_name: rabbitmq-server
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
      - 25672:25672
      - 4369:4369
      - 15671:15671
      - 5671:5671
    volumes:
      - './rabbitmq_data:/var/lib/rabbitmq'
      - './rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf'
     #- './hosts:/etc/hosts'