version: '3'
services:
  mongodb:
    image: mongodb/mongodb-community-server:8.0.1-ubuntu2204
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: yourpassword
    ports:
      - 27017:27017
    volumes:
      - ./mongodb_data:/data
