version: '3.8'
services:
  mongodb:
    image: mongodb
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: yourpassword
    ports:
      - 27017:27017
    volumes:
      - ./mongodb_data:/data