version: "3.7"
services:
  minio:
    image: minio/minio:RELEASE.2025-04-03T14-56-28Z
    restart: always
    env_file:
      - minio.env
    command: server /data --console-address ":9001"
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - ./minio-data:/data